apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment-5
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-5
        image: nginx:1.14.2
        ports:
        - containerPort: 80
